### ISSUE TITLE
Assignment of Slim Symbols in SqlCommand Tables not working for me

### ISSUE THREAD

**Issue by nicholas-prozesky** [six42/jdbcslim#1]
Hi,

I've been trying to get the H2 1ASimpleExample test working, but it seems like the assignment to Slim symbols in the table isn't working.
Is there something I'm missing to get it to work correctly?

Regards
Nicholas

**Comment by six42** [comment]
Hi Nicholas,

Thanks for giving jdbcSlim a try.

The symbol assignment requires a very recent FitNesse version with  the below PR.
This should be any version build after 7-Oct-2015

Take the daily build or build a version yourself.

https://github.com/unclebob/fitnesse/pull/779

**Comment by nicholas-prozesky** [comment]
Okay, great. I'm running 20150814, so that's likely to be the problem. I'll try and pull a later version. Thanks muchly.

**Comment by nicholas-prozesky** [comment]
Yip. That was the problem. Thanks for the help. Really appreciate it!
