### ISSUE TITLE
Make jdbcslim releases available in Maven Central

### ISSUE THREAD

**Issue by fhoeben** [six42/jdbcslim#10]
To include jdbc in a FitNesse installation it would be nice if jdbcslim could be obtained from Maven Central, and not just from the GitHub releases page.

Especially in corporate environments downloading stuff from GitHub is often not allowed, whereas they often have a proxy for Maven Central which allows them to get dependencies from there.

To be added to Maven Central the project has to be open source (which it is not currently based on its LICENSE.txt), which also makes it easier to introduce in corporate environments.

Initial setup of upload is a bit of a hassle, but uploading releases after that (or adding more libraries/projects), is not much work at all. I suggest using Sonatype OSS Repository Hosting: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by six42** [comment]
Hi Fried,

I am in favour of this.
Thanks for adding the link to the HowTo.
I will give it a try and 
I hope end of September I can look at this.

**Comment by fhoeben** [comment]
Will you be able to look at this soon?
Thanks

**Comment by six42** [comment]
I am on it.

**Comment by fhoeben** [comment]
With my pull requests merged I'm looking forward to this more than ever (don't forget to make dbfit [optional](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) in the pom.xml  ;-))

**Comment by six42** [comment]
First upload done. 
look at https://oss.sonatype.org/content/groups/public/com/github/six42/jdbcslim/1.2.0/

Does it looks ok for you?

**Comment by six42** [comment]
just noticed that everything is there except the jar itself :(
Need to check ...

**Comment by fhoeben** [comment]
I also expected to see the pom.xml there.

Will you merge in my suggested pom changes before final upload?

**Comment by six42** [comment]
resend as 1.2.1 now it looks correct. 
 https://oss.sonatype.org/content/groups/public/com/github/six42/jdbcslim/1.2.1/

**Comment by fhoeben** [comment]
Looks good. I assume this is released to end up in Maven central?
