### ISSUE TITLE
Make dbfit dependency optional

### ISSUE THREAD

**Issue by fhoeben** [six42/jdbcslim#12]
As far as I've been able to establish (in code and documentation) dbfit is only needed for encryption.

If that is correct can the code be updated to make this dependency optional (i.e. no direct references to its dbfit.util.crypto.Crypto* classes in PropertiesLoader)?

dbfit, with its dependencies when gotten from Maven Central or GitHub, is quite big (+- 18MB) so not adding it to a test project when it is not actually used seems desirable to me.

**Comment by six42** [comment]
Hi Fried,
Your analysis is 100% correct. :-)

Getting the dependency removed was on my list but it moved very much to the end as other things are to me more important.

If it is important for you I am happy to integrate your PR.

**Comment by fhoeben** [comment]
Closed via #19
