### ISSUE TITLE
Issues integrating JDBC Slim into FitNesse

### ISSUE THREAD

**Issue by sej2105** [six42/jdbcslim#18]
Hi,

I am new to FitNesse and am trying to download jdbcslim and get that working with  my current installation. 

I have downloaded the project and followed the build instructions, however when running the userGuide Suite to see if the tests run, all seem to have failed with exceptions. 

Examples are given below: Page include failed because the page PlugIns.JdbcSlim.XxTestMoreDrivers.HtwoTest.SuiteSetUp does not exist

The instance decisionTable_2.ID. does not exist

These are just a few examples of the exceptions I am seeing. I may be doing something wrong with the installation or build, apologies for that i am quite new to this and have been asked to implement this into  my organisation. 

Any  help or guidance in basic set up options would be highly appreciated as this is causing a delay and i am not sure how to resolve the issue. 

Many thanks

**Comment by Unforgettable631** [comment]
Did you follow the installation guide provided below and adjusted all the !path's correctly to your installation path?
http://rawgit.com/six42/jdbcslim/master/JdbcSlim.htm#JdbcSlim.Installation

Or did you follow the buildinstructions (or both :)) on this location:
https://github.com/six42/jdbcslim/blob/master/FitNesseRoot/PlugIns/JdbcSlim/Installation/BuildInstructions.wiki

Can you provide more info about your current installation and which steps you took to embed jdbcslim and how you run FitNesse?

**Comment by six42** [comment]
closing this as no update for a long time after instructions have been given.
