### ISSUE TITLE
Getting Method not found for Inputs and Output column While using SQLCommand

### ISSUE THREAD

**Issue by bhatt** [six42/jdbcslim#2]
Hi,

I am trying to use jdbcslim on my project. It is giving me an error "Method ORDER_NUMBER[0] not found in six42.fitnesse.jdbcslim.SQLCommand." I am getting this for all the input and output columns for SQLCommand fixture.

e.g: I am expecting ORDER_NUMBER, TASK_DESCRIPTION and STATUS as output of a query. When i run my test i get an Method not found error. 

Appreciate your help!

**Comment by bhatt** [comment]
I am using fitnesse version "v20151230"

**Comment by six42** [comment]
Hi Bhatt,

happy to help.
Can you send me the wiki page you try to test.

**Comment by bhatt** [comment]
Hey,
Thanks for the reply! Here is what i am trying to do:

!define orderNumber {123456789}

!** Setup jdbcSlim
|import                 |
|six42.fitnesse.jdbcslim|

|define table type  |
|SQLCommand as Table|
**!

!** Driver Specific Setup
!path plugins\jdbcslim\ojdbc6-11.jar

!|Define Properties|TestDatabaseST8                                       |
|key               |value                                                 |
|jdbcDriver        |oracle.jdbc.OracleDriver                              |
|#DBURL            |jdbc:h2:~/h2db                                        |
|DBURL             |jdbc:oracle:thin:@nmsls8d1.snt.bst.bls.com:1521:ljb8t1|
|DBUSER            |nimbus                                                |
|DBPASSWORD        |jb0ss4d2015                                           |
|#DBAUTOCOMMIT     |true                                                  |
|CMD               |                                                      |

**!



!|Define Properties|GETORDERSTATUS |
|key               |value          |
|.include          |TestDatabaseST8|
|DBConnection      |OLDBConnection |


!|SQLCommand   |TestDatabaseST8|SELECT af.flowableid as ORDER_NUMBER, tk.description as TASK_DESCRIPTION, DECODE(tk.status, 0, 'NOT_STARTED', 1, 'IN_PROGRESS', 2, 'SUCCEEDED', 3, 'FAILED',5,'NA', tk.status) as STATUS from abstractflowable af, workflow wf, activity act, task tk where af.id=wf.flowable_id(+) and wf.id=act.workflow_id(+) and act.id=tk.activity_id(+) and af.flowableid = '%X%' and tk.description like 'Receive Transport Request from OMS' order by tk.starttime desc|RETRY=50:60000|
|X             |ORDER_NUMBER?  |TASK_DESCRIPTION?                                                                                                                                                                                                                                                                                                                                                                                                                                              |STATUS?       |
|${orderNumber}|${orderNumber} |Receive Transport Request from OMS                                                                                                                                                                                                                                                                                                                                                                                                                             |SUCCEEDED     |

**Comment by six42** [comment]
Hi Bhatt,

thanks for sharing.
One  pipe symbol is missing:  

|define table type |
|SQLCommand | as Table|

**Comment by bhatt** [comment]
Thanks!! It worked!!

**Comment by six42** [comment]
Pleasure!

Please 'STAR' jdbcslim if you find it useful.
