### ISSUE TITLE
`getRowCount()` should return 0 if first non-header row does not have values

### ISSUE THREAD

**Issue by fhoeben** [six42/jdbcslim#21]
Currently `getRowCount()` just counts the number of rows beyond the header, but if no results are returned there is a first row. So `getRowCount()` returns 1. 
But that first row does not have any values, leading to errors later on when one calls `getColumnValueByName()`.

When a query returns no results the 'row count' should be 0, correct?

Is that empty row required for the usage as 'table', or could it just be removed altogether?

**Comment by Unforgettable631** [comment]
We are also facing this issue just a few days ago. Looking forward for when your fix will be merged!
