### ISSUE TITLE
List version 1.2.1 as release on GitHub

### ISSUE THREAD

**Issue by fhoeben** [six42/jdbcslim#24]
The latest release available in maven central is 1.2.1 (based on https://mvnrepository.com/artifact/com.github.six42/jdbcslim), but this version is not listed on the releases page in GitHub. Maybe you should also mention it is available in Maven Central somewhere in README or UserGuide?

Also, looking at the current master's `build.gradle`, I believe that is still building a 1.2.0. Should that be something like 1.2.2-SNAPSHOT?

**Comment by six42** [comment]
Good questions.
I added a release on GitHub 1.2.2 and pushed to maven central as well as a first step.
Keeping the version in build.gradle up to date is currently manual. Is there a way to automate this?

**Comment by fhoeben** [comment]
I don't know how to automate the version update. Sorry.
