### ISSUE TITLE
SQLCommand - dbExecute:Method not supported

### ISSUE THREAD

**Issue by abhash2610** [six42/jdbcslim#29]
I'm getting an error when I'm running SQLCommand fixture.
`Database execution failed:Method not supported`

I'm referring the example **Constructor with two parameter** and below is how my test page looks like:

```
!define TEST_SYSTEM {slim} 

|import|
|six42.fitnesse.jdbcslim|

|define table type|
|SQLCommand|as Table|

'''Connect to Database'''

!| Define Properties | DatabaseSetup |
| key | value |
| jdbcDriver | org.apache.hive.jdbc.HiveDriver |
| DBURL | jdbc:hive2://host:port/default | 
| DBUSER | user |
| DBPASSWORD | pass |

!| SQLCommand | DatabaseSetup | SELECT value as test_value FROM mytable |
|test_value?|     ---->>  Database execution failed:Method not supported
|N|
```

Is there anything I'm missing here?

**Comment by Unforgettable631** [comment]
This exception is coming from the hive-jdbc driver. Which version of the driver do you use? Do you get more (Execution log) error information if you use the debug parameter as key value option in your database setup?
`| debug | true |`

It could be a driver mismatch, but it can also be that the method is not (yet) supported:
https://github.com/apache/hive/blob/branch-1.2/jdbc/src/java/org/apache/hive/jdbc/HiveResultSetMetaData.java

**Comment by abhash2610** [comment]
I'm not getting extra information with | debug | true |
Can you please help me pointing out the excerpt from the code where this method is being called?

**Comment by abhash2610** [comment]
@Unforgettable631 thanks a lot. I resolved it by tweaking the code. It was the prepare call method which was throwing the method not supported exception.
