### ISSUE TITLE
Surplus and Missing rows not reported

### ISSUE THREAD

**Issue by McLFaberge** [six42/jdbcslim#31]
I'm migrating my old DBFit tests to JDBCSlim. One feature that DBFIT had that I'm now missing was the ability to report missing and surplus rows.
Currently in JDBCSlim when I've got a row missing or surplus in the beginning or middle of my expected output, it throws the rest of the table off, instead of identifying the mistake.

Would it perhaps be possible to do row matching on unique (set of) values?

**Comment by six42** [comment]
This should be the default behaviour. 
Except if you set the subquery flag.

You need to indicate what columns make a row unique.
Check these examples:

https://six42.github.io/fitnesse-blog/PlugIns.JdbcSlim.UserGuide.6OutputOptions.Sorting.html


Am March 21, 2019 7:13:10 AM UTC schrieb McLFaberge <notifications@github.com>:

**Comment by McLFaberge** [comment]
Thank you for your reply.
I've added SORT as a parameter and added < to my output column.
It all seems to work great now!
