### ISSUE TITLE
Empty row when no records returned in Table:SQLCommand

### ISSUE THREAD

**Issue by McLFaberge** [six42/jdbcslim#32]
This issue was briefly addressed in [issue #21](https://github.com/six42/jdbcslim/issues/21).

When the expected result should return 0 records, an empty row is created. When one result is returned the test will pass while it should fail.

Example:

table:SQLCommand | ${DB} | ${SQLquery} | QUERY
-----------------------|------ |---------------|-------
NAME | ID | USERNAME | EMAIL

**Comment by six42** [comment]
To make it clear to the reader of the test case that zero results are expected I test the rowcount as described in : https://six42.github.io/fitnesse-blog/PlugIns.JdbcSlim.UserGuide.6OutputOptions.TotalOnly.html

Or use a script as in the example of the PR 22

!|Script|SQLCommand |ScriptDefinition        |
		|run    |select * from TestData where id='-1'|
		|check  |getRowCount|0                       |
		

Would one of these approches help you?

**Comment by McLFaberge** [comment]
Thank for your quick reply!

I am actually using the geRowCount in part one of my test. The thing is that when rowcount > 0, we need to also report the surplus rows.

**Comment by Unforgettable631** [comment]
Does using a regex for empty string help you?

For example:
!define regex {=~/\A\z/}

```
!|table:SQLCommand | ${DB} | ${SQLquery} | 
|NAME? |
|${regex}|

```

When there are surplus rows it would displayed as:
```
!|table:SQLCommand | ${DB} | ${SQLquery} | 
|NAME? |
|=~/\A\z/ not found in: foo|
|[+] bar|
```

You can also combine this with the method six42 mentioned.

**Comment by McLFaberge** [comment]
That works brilliantly!
Combined with the method that six42 mentioned, I can now run all my old DBFit tests using JDBCslim

Thank you @Unforgettable631 & @six42

**Comment by six42** [comment]
Congratulation to your successful migration!

Thanks @Unforgettable631 for your  advice.
