### ISSUE TITLE
Show / use resultsheet without header columns

### ISSUE THREAD

**Issue by Gertray13** [six42/jdbcslim#37]
I couldn't find it in the documentation, but is there a way to use the resultsheet or when echo-ing the resultsheet (or both) without printing the header columns?

For example, I want to use / generate an outcome for another scenario.

```
!|script|SQLCommand|TestDatabase|
|run|${query}| --> output of this are multiple rows 'for example insert queries' I want to use without header columns
|$savedResultQuery=|resultSheet|

!|script|SQLCommand|OtherDatabase|
|run|${savedResultQuery}|
```
Or by just printing it with a parameter like?
```
|!-Table:SheetEcho-!|$savedResultQuery|ShowNoHeaders|

```

**Comment by six42** [comment]
Hi @Gertray13,

sorry for comming back late to you question. 
The result sheet is just a list of lists. So you can do.

!|script|SQLCommand|TestDatabase|
|run|${query}| --> output of this are multiple rows 'for example insert queries' I want to use without header columns
|$savedResultQuery=|resultSheet|

!|script| $savedResultQuery|
|$last=|size|
|$rsNoHeader=|sub |1 |list| $Last|

!|Table:SheetEcho|$rsNoHeader|

**Comment by Gertray13** [comment]
Thank you @six42! I should have play around more to get that solution myself. Many thanks.
