### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by keetron** [six42/jdbcslim#4]
I am running into compilation errors when using the ant script to compile. I added fitnesse-standalone.jar (06112016 version) and dbfit.jar, all compilation errors are on the fitnesse file.
Let me try with the version before that or can you tell me what version you used to compile?

**Comment by six42** [comment]
Hi @keetron
 
Which OS are you using and which Java version
I just started a fresh build on Linux and after adding the dependencies the build of the jar worked. 
the test cases needed some more updates but are all good now.
And I hope i didn't broke the Windows build.

I put all my steps in the file 
https://github.com/six42/jdbcslim/blob/master/FitNesseRoot/PlugIns/JdbcSlim/Installation/BuildInstructions.wiki

I hope this solves all your trouble.

**Comment by Unforgettable631** [comment]
When I follow the BuildInstructions I can build the jar as well. Running on Windows.

**Comment by six42** [comment]
👍
Thanks for the confirmation.

**Comment by keetron** [comment]
I know I am late with responding but everything happened at the same time.
During the implementation of jdbcSlim we found that all we want to do seems to be already possible so no compilation is needed at this time. It might change later, but good to know all is working as expected.

**Comment by six42** [comment]
Hi Keetron, 

great to hear that jdbcSlim it is useful for you out of the box. 🥇 
You are welcome to open more issues if you close them with such comments :)
