### ISSUE TITLE
Trouble with installation regarding root page and suite setup page

### ISSUE THREAD

**Issue by michaelklijn** [six42/jdbcslim#41]
Dear six42,

I'm currently also in the proces of setting up a FitNesse instance together with your JdbcSlim solution for database testing. However I'm getting stuck on the installation page at the end, as you state: "!2 To build your own test pages 1. include this page on the root page of your suite 2. include the SuiteSetup page or a page with similar content in the setup of your suite" What page do you mean at point 1, with 'this page'? And do you have an example (screenshot or something alike) of both point 1 and 2, the root page and the SuiteSetup page regarding the content needed?

Thanks in advance!

You can always reach me on: michael.klijn@closesure.nl

Regards,

Michael Klijn

**Comment by Unforgettable631** [comment]
Hi @michaelklijn,

I hope I can answer your questions.
1. As in, the actual page this sentence is on :-).  So, that's the `Installation.wiki`.  That page contains loading the classes / fixtures of jdbcSlim('s dependencies) and defines the variables used in the jdbcSlim acceptance tests.
2.  For the `SuiteSetup` you need to have at least an import section and if you use jdbcSlim, also the define table type:
![image](https://user-images.githubusercontent.com/26714288/81428333-6bcf7c00-915c-11ea-90a7-9a854cbdf69c.png)

What kind of setup do you have now? Do you use jdbcSlim alone or did you embed jdbcSlim as a plugin in an existing FitNesse installation?

We use the latter one, I can try to give you an example when I have more time to create one.

**Comment by michaelklijn** [comment]
Hi @Unforgettable631,

I also installed the fitnesse standalone installation and on top of that I am embedding jdbcslim as a plugin. Starting over with the installation as we speak

**Comment by michaelklijn** [comment]
@Unforgettable631, if possible it would be great to walk through the installation steps together. Please let me know around what time you might be online and we might setup a short Teams meeting so I can also share screen... 

The following is already confusing me a bit:
 !2  Installation Path 
Adjust the below path if you installed at a different location
This path is relative to the folder in which FitNesse got started 
!define LibInstallPath {${Rootpath}/plugins/jdbcslim/}           However, when I installed Fitnesse-standalone.jar I dont have a plugins (small p) folder on the root, I do see a Plugins (with capital P) in the FitNesseRoot directory.

The Jdbc Slim Library - always required
!path ${LibInstallPath}${JdbcSlimLib}                 Does this indeed say that I have to create a directory JdbcSlimLib?

As you can see, perhaps it is a lot more convenient for us both to have a short meeting. I would really appreciate it and already appreciate the help so far!

Regards,
Michael
