### ISSUE TITLE
I'd like a select where you can store the returned value of a cell in a variable

### ISSUE THREAD

**Issue by pvbemmelen62** [six42/jdbcslim#48]
<pre>
!|SQLCommand|StartupDatabase|SELECT TOP 1 * FROM BV.Bands|Query        |
|BandName?  |BandLeader?    |BandAge?                    |BandCount?   |
|=~/.*/     |=$firstLeader? |=~/.*/                      |=~/.*/|=~/.*/|
*!

|Import           |
|fitnesse.fixtures|

|Library                      |
|fitnesse.fixtures.EchoFixture|

!|script|echo fixture   |
|show   |echo|$firstLeader|
</pre>

This would for instance allow for checks for equality between values from different tables.

**Comment by six42** [comment]
Hi Paul,

Did you checked: https://six42.github.io/fitnesse-blog/PlugIns.JdbcSlim.UserGuide.7UsingSqlInScriptsAndScenarios.SymbolAssignmentOfResults.html

**Comment by pvbemmelen62** [comment]
Thanks, that's exactly what I need.
