### ISSUE TITLE
execute script from file

### ISSUE THREAD

**Issue by keetron** [six42/jdbcslim#5]
Now before anything else, I did not look very hard yet, but how would I go and start an SQL script from a file? This would be useful for really huge datasets...

Another one would be how to do a test to compare two result sets from two queries, to do a source/target compare?

**Comment by six42** [comment]
File loading - not a standard feature
Put your data on a wiki - I didn't reached page size limits yet.
If you need - it add it. Should be simple.

Source target compare is like before after compare ,look at :
https://github.com/six42/jdbcslim/blob/master/FitNesseRoot/PlugIns/JdbcSlim/UserGuide/2KeyBenefits/2TestingOnSideEffects.wiki

**Comment by keetron** [comment]
File loading I will (probably) add, it might be required by the userbase here.

The compare works as expected, now I would like to refine the result table in that it shows only records with a difference. Is that a default filter that can be applied? Else I might add that as well.

**Comment by six42** [comment]
The compare result can't be filtered further.
For automated tests the expectation is that all tests pass and you don't look at the details. Showing just an empty table in this case would not create trust.

I hide the table in a collapsed section to keep the space on the screen organized.

But a PR is welcome if it helps your userbase.

**Comment by keetron** [comment]
Those are really good point, thanks for this.
Indeed trust is important and an empty table helps nobody.

**Comment by keetron** [comment]
Some experimentation leads me to believe the scenario's as supported by the FitNesse framework are not easily used/implemented when calling the jdbcSlim fixture.
If I am wrong, can you give a short example on how I would go and implement a scenario that would run the same query in two test scripts using scenario's?

**Comment by keetron** [comment]
Sorry, I RTFM'ed.
