### ISSUE TITLE
SQLServer binary data column when queried value misses 0x prefix

### ISSUE THREAD

**Issue by pvbemmelen62** [six42/jdbcslim#50]
**Problem:**
With an MS SQLServer database, when I do a WHERE query on a value from a binary(32) column, and use a value obtained from an earlier query, I have to prefix the value in the WHERE query with 0x .
That's not nice, because what I want is to be able to use the value as it was returned from the earlier query.

**Explanation:**
In a SQL server database I have table KNT_0104_Zaak_Werksoort  that has 5 columns,
one of which is KLM_Zaak_Werksoort_HKey  with type binary(32) .

https://learn.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-ver16
states:
<pre>
binary [ ( n ) ]

Fixed-length binary data with a length of n bytes, where n is a value from 1 through 8,000. The storage size is n bytes.
</pre>

I do first a query that returns values from the first row,
and I store the value of KLM_Zaak_Werksoort_HKey   in slim variable firstKey .
Next I want to check that a query with a WHERE clause on that value of firstKey ,
returns a result from matching row 1.

I find that in the WHERE clause, I need to prefix the value for the firstKey, with 0x .
Otherwise the second query won't match any row.

<pre>
!* query first row
!|SQLCommand             |StartupDatabase|SELECT TOP 1 * FROM BV.KNT_0104_Zaak_Werksoort|
|KLM_Zaak_Werksoort_HKey?|MD_GeldigVan?  |MD_GeldigTot?    |MD_LaadDatum?   |MD_Bron?   |
|$firstKey=             |=~/.*/         |=~/.*/           |=~/.*/          |=~/.*/     |
*!

!* where query
!|SQLCommand            |StartupDatabase|SELECT MD_GeldigVan FROM BV.KNT_0104_Zaak_Werksoort WHERE KLM_Zaak_Werksoort_HKey = 0x%KLM_Zaak_Werksoort_HKey%|
|KLM_Zaak_Werksoort_HKey|MD_GeldigVan?                                                                                                                  |
|$firstKey             |=~/.*/                                                                                                                         |
*!
</pre>

I looked in the jdbcslim code, at where the value that is assigned to firstKey, is obtained :
<pre>
six42.fitnesse.jdbcslim.SQLCommand  convertRSIntoTable :

    while (rs.next()) {
      oneRow = new ArrayList<String>();
      for (int i = 1; i <= columnCount; i++) {
>>>     oneRow.add(rs.getString(i));
        if (Properties().isDebug()) System.out.println("Row:" + i + ":" + rs.getString(i));
      }
      appendOrExtendRow(resultTable, oneRow, rowCount++, extend, summaryOnly);
    }

</pre>

I see that rs is an object of type
  com.microsoft.sqlserver.jdbc.SQLServerResultSet
and from the ms sqlserver jdbc driver (mssql-jdbc-11.2.1.jre11.jar) .

**Question:**
Should the getString() method from SQLServerResultSet add the prefix 0x .
Of should method convertRSIntoTable  from SQLCommand add the prefix ,
by using something more advanced than getString()  ?

**Comment by pvbemmelen62** [comment]
Maybe relevant that "Microsoft SQL Server Management Studio" displays the value for that binary column with the prefix 0x ?

**Comment by six42** [comment]
Hi Paul,

I see you have a workaround by adding the 0x before the variable in the select query.

It looks a bit inconsistent how the rs getString function is implemented. Ideally it should be fixed there.

Did you tried the syntax with inline parameters. Here you define the type which might help.
The type number is from the jdbc implementation:

Inline Parameters in SQL commands are given as ?{Input Column>Output Column:Type(Scale)=Default Value}

https://six42.github.io/fitnesse-blog/PlugIns.JdbcSlim.UserGuide.4TheMappingBetweenTestDataAndCommands.StoredProcedures.WithParameterDefinitionsInline.html

If it doesn't work it could be another place to fix it.

**Comment by pvbemmelen62** [comment]
Indeed, the syntax with inline parameters gives the right result, i.e. it matches the correct row.
I used ?{KLM_Zaak_Werksoort_HKey:-2(100)}  as shown below.
I found the value of -2  in the source code of class java.sql.Types .

<pre>
!* where query
!|SQLCommand            |StartupDatabase|SELECT MD_GeldigVan FROM BV.KNT_0104_Zaak_Werksoort WHERE KLM_Zaak_Werksoort_HKey = ?{KLM_Zaak_Werksoort_HKey:-2(100)}|
|KLM_Zaak_Werksoort_HKey|MD_GeldigVan?                                                                                                                  |
|$firstKey             |=~/.*/                                                                                                                         |
*!
</pre>

Lines in source  of java.sql.Types that contain "public":
<pre>
public class Types {
        public final static int BIT             =  -7;
        public final static int TINYINT         =  -6;
        public final static int SMALLINT        =   5;
        public final static int INTEGER         =   4;
        public final static int BIGINT          =  -5;
        public final static int FLOAT           =   6;
        public final static int REAL            =   7;
        public final static int DOUBLE          =   8;
        public final static int NUMERIC         =   2;
        public final static int DECIMAL         =   3;
        public final static int CHAR            =   1;
        public final static int VARCHAR         =  12;
        public final static int LONGVARCHAR     =  -1;
        public final static int DATE            =  91;
        public final static int TIME            =  92;
        public final static int TIMESTAMP       =  93;
        public final static int BINARY          =  -2;
        public final static int VARBINARY       =  -3;
        public final static int LONGVARBINARY   =  -4;
        public final static int NULL            =   0;
        public final static int OTHER           = 1111;
        public final static int JAVA_OBJECT         = 2000;
        public final static int DISTINCT            = 2001;
        public final static int STRUCT              = 2002;
        public final static int ARRAY               = 2003;
        public final static int BLOB                = 2004;
        public final static int CLOB                = 2005;
        public final static int REF                 = 2006;
    public final static int DATALINK = 70;
    public final static int BOOLEAN = 16;
    public final static int ROWID = -8;
    public static final int NCHAR = -15;
    public static final int NVARCHAR = -9;
    public static final int LONGNVARCHAR = -16;
    public static final int NCLOB = 2011;
    public static final int SQLXML = 2009;
    public static final int REF_CURSOR = 2012;
    public static final int TIME_WITH_TIMEZONE = 2013;
    public static final int TIMESTAMP_WITH_TIMEZONE = 2014;
</pre>

However, using this inline parameter (better name: inline type definition?) is no more robust than using 0x as a prefix;
both require specific spec for particular column. The value in the where clause still is not simply the value obtained from an earlier query.

Should I close this issue now ?

**Comment by six42** [comment]
Hi Paul,

if your value would not be binary but a string value you would also need to add quotes **''** arround the variable.
In short you need to somehow know the type when you write an SQL query anyway.

Do you see an elegant way to make it simpler? 
I agree the inline types make it robust but not simpler.

!* where query
!|SQLCommand            |StartupDatabase|SELECT MD_GeldigVan FROM BV.KNT_0104_Zaak_Werksoort WHERE KLM_Zaak_Werksoort_HKey = **'%KLM_Zaak_Werksoort_HKey%'**|
|KLM_Zaak_Werksoort_HKey|MD_GeldigVan?                                                                                                                  |
|$firstKey             |=~/.*/                                                                                                                         |
*!

**Comment by pvbemmelen62** [comment]
I guess knowledge of the type of the column is required, and maybe that is not too much of a restriction.
Doing a query where you don't know the type, maybe is not a common use case.
