### ISSUE TITLE
[CI/CD pipeline] java.lang.Exception: java.lang.RuntimeException: decrypt of *** failed. Wrong Key Store used?

### ISSUE THREAD

**Issue by McLFaberge** [six42/jdbcslim#53]
When running tests usin jdbcslim within a pipeline using a docker image (Ubuntu 20.04 LTS) I always seem to get this exception:
`java.lang.Exception: java.lang.RuntimeException: decrypt of *** failed. Wrong Key Store used?`

My keystore is located in _<project_name>_/wiki/keyStore/.dbfit.jks
In my "Define Properties" table I've tried the following options:
```
| .keyStoreLocation | ./keyStore  |
| .keyStoreLocation | ./keyStore/ |
| .keyStoreLocation | keyStore    |
| .keyStoreLocation | keyStore\   |
```

All seem to work when running them on Windows (IntelliJ), but not in the pipeline.
I'm currently using jdbcslim as a dependency in my already existing project pom.xml.

**Comment by six42** [comment]
Can you share the execution log how the slim service is started in Windows and in Docker?

**Comment by McLFaberge** [comment]
After a good night's sleep I seemed to have figured it out. It has to do with the project root according to Java when running as standalone vs. running in CI/CD pipeline.
project root for standalone is <project_name>/wiki/
project root when running in pipeline (FixtureDebugTest) is <project_name>/

There are multiple ways to solve this. For me, I now have 2 copies of the key store in my project.

**Comment by Unforgettable631** [comment]
If you are looking for a simple solution, we had the same setup (keystore dir in the wiki dir) and fixed it by using the [RootPath](https://github.com/unclebob/fitnesse/blob/478aac77d993f8b23f76d415189dd927ed326274/FitNesseRoot/FitNesse/UserGuide/AdministeringFitNesse/CommandLineArguments/content.txt#L7) variable which you might want to try yourself as well:

`!define keystore_location {${RootPath}/keyStore/}`

`| .keyStoreLocation | ${keystore_location} | `

**Comment by six42** [comment]
Glad you fixed it by sleeping :)

**Comment by six42** [comment]
That's elegant!
Thanks for sharing @Unforgettable631
