### ISSUE TITLE
Call a stored procedure

### ISSUE THREAD

**Issue by keetron** [six42/jdbcslim#6]
I did some internet searching and there is it mentioned I can use ScriptFixture from jdbcSlim to call a stored procedure, but no mention of this is in the manual.
How would I go call a stored procedure using jdbcSlim according to you?

**Comment by six42** [comment]
Scriptfixture is a Fit construction which is not supported.

Slim scripts are. Look at https://github.com/six42/jdbcslim/blob/master/FitNesseRoot/PlugIns/JdbcSlim/UserGuide/7UsingSqlInScriptsAndScenarios.wiki

Stored procedures can be called from scripts and from decision tables:
https://github.com/six42/jdbcslim/tree/master/FitNesseRoot/PlugIns/JdbcSlim/UserGuide/4TheMappingBetweenTestDataAndCommands/StoredProcedures

The exact syntax might vary based on the database. But is the same as if you would call a sp from java code directly. Just google for jdbc and your database type.

**Comment by keetron** [comment]
What I gather from this is two things:
1. I should read the manual more
2. jdbcSlim is set up as a thin layer around the java jdbc functionality.

Thanks :smile:

**Comment by keetron** [comment]
It seems SapHana is a special beast, I keep getting a syntax error when using straight forward calls to the SP.
